version: '3'
services:
  weatherapp-back:
    build: ./backend
    command: node_modules/nodemon/bin/nodemon.js
    ports:
      - "9000:9000"
      - "9229:9229"
    volumes:
      - ./backend:/var/www/weatherapp/backend
    environment:
    - NODE_ENV=development
  weatherapp-front:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
    - ./frontend:/var/www/weatherapp/frontend